on:
  push:
    tags:
      - "*"

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: 'Genshin-Discord-Bot_${{ github.ref_name }}.zip'
          exclusions: '*.git*'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: 'Genshin-Discord-Bot_${{ github.ref_name }}.zip'